# Generated by Django 5.2.17 on 2026-09-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hosts.directory', verbose_name='父目录')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
            },
        ),
        migrations.CreateModel(
            name='DirectoryHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='目录内排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='挂载时间')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hosts.directory')),
            ],
            options={
                'verbose_name': '目录-主机挂接',
                'verbose_name_plural': '目录-主机挂接',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='主机名')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('port', models.PositiveIntegerField(verbose_name='端口')),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=16, verbose_name='操作系统')),
                ('connect_type', models.CharField(choices=[('ssh', 'SSH'), ('rdp', 'RDP')], max_length=16, verbose_name='连接方式')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('online', '在线'), ('offline', '离线')], default='unknown', max_length=16, verbose_name='在线状态')),
                ('status_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='状态探测时间')),
                ('username', models.CharField(default='', max_length=128, verbose_name='登录账号')),
                ('_password', models.BinaryField(blank=True, db_column='password_encrypted', null=True, verbose_name='登录口令(密文)')),
                ('_private_key', models.BinaryField(blank=True, db_column='private_key_encrypted', null=True, verbose_name='私钥(密文)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('directories', models.ManyToManyField(blank=True, related_name='hosts', through='hosts.DirectoryHost', to='hosts.directory')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
        migrations.AddField(
            model_name='directoryhost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hosts.host'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['parent'], name='hosts_direc_parent__121432_idx'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_dir_sibling_name'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['status'], name='hosts_host_status_547f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['os_type'], name='hosts_host_os_type_12e825_idx'),
        ),
        migrations.AddIndex(
            model_name='directoryhost',
            index=models.Index(fields=['directory', 'position'], name='hosts_direc_directo_3718e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='directoryhost',
            constraint=models.UniqueConstraint(fields=('directory', 'host'), name='uniq_dir_host'),
        ),
    ]
