# Generated by Django 5.2.17 on 2026-09-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='admin', max_length=64, verbose_name='操作人')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('target_type', models.CharField(max_length=32, verbose_name='对象类型')),
                ('target_name', models.CharField(blank=True, default='', max_length=255, verbose_name='对象名称')),
                ('detail', models.CharField(blank=True, default='', max_length=512, verbose_name='详情')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('info', '信息')], default='success', max_length=16, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ops_auditlo_created_00770a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作业名称')),
                ('host_name_snapshot', models.CharField(default='', max_length=128, verbose_name='主机名快照')),
                ('command', models.TextField(blank=True, default='', verbose_name='命令/脚本')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=16, verbose_name='状态')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='hosts.host', verbose_name='目标主机')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ops_job_created_0ee467_idx'), models.Index(fields=['status'], name='ops_job_status_3e8eb3_idx')],
            },
        ),
    ]
