# Generated by Django 4.2.30 on 2026-09-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='admin', max_length=64, verbose_name='操作人')),
                ('command', models.TextField(verbose_name='命令')),
                ('host_count', models.PositiveIntegerField(default=0, verbose_name='目标机器数')),
                ('dangerous', models.BooleanField(default=False, verbose_name='命中危险规则')),
                ('confirm_reason', models.CharField(blank=True, default='', max_length=512, verbose_name='确认原因')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '命令批次',
                'verbose_name_plural': '命令批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='error_category',
            field=models.CharField(blank=True, choices=[('timeout', '连接超时'), ('auth', '认证失败'), ('config', '凭据未配置'), ('connection', '无法连接'), ('privilege', '权限不足'), ('interrupted', '已中断'), ('remote', '命令返回非零退出码'), ('unknown', '其它异常')], default='', max_length=16, verbose_name='异常类别'),
        ),
        migrations.AddField(
            model_name='job',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='异常信息'),
        ),
        migrations.AddField(
            model_name='job',
            name='interrupted',
            field=models.BooleanField(default=False, verbose_name='用户中断'),
        ),
        migrations.AddField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('job', '普通作业'), ('quick', '快捷命令')], default='job', max_length=16, verbose_name='执行类型'),
        ),
        migrations.AddField(
            model_name='job',
            name='output',
            field=models.TextField(blank=True, default='', verbose_name='完整输出'),
        ),
        migrations.AddField(
            model_name='job',
            name='output_truncated',
            field=models.BooleanField(default=False, verbose_name='输出曾被截断'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['kind', '-created_at'], name='ops_job_kind_3a6bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['host', '-created_at'], name='ops_job_host_id_505ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='commandbatch',
            index=models.Index(fields=['-created_at'], name='ops_command_created_8f474d_idx'),
        ),
        migrations.AddIndex(
            model_name='commandbatch',
            index=models.Index(fields=['actor', '-created_at'], name='ops_command_actor_bfc47a_idx'),
        ),
        migrations.AddField(
            model_name='job',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ops.commandbatch', verbose_name='所属批次'),
        ),
    ]
